# Name of the workflow
name: Deploy to GKE

# Trigger this workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  # Job for building and pushing the Docker image
  build-and-push:
    runs-on: ubuntu-latest
    steps:
    # Step to checkout the source code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step to build the Docker image
    - name: Build Docker image
      run: docker build -t ${{ secrets.DOCKER_REPOSITORY }}:v6 .

    # Step to login to Docker Hub
    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    # Step to push the built Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_REPOSITORY }}:v6

  # Job for deploying to Google Kubernetes Engine (GKE)
  deploy:
    # Ensure that this job only runs after the build-and-push job completes successfully
    needs: build-and-push
    runs-on: ubuntu-latest
    steps:
    # Step to checkout the source code from the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Step to set up the Google Cloud (gcloud) CLI
    - name: Setup gcloud CLI
      uses: google-github-actions/setup-gcloud@v0.2.1
      with:
        service_account_key: ${{ secrets.GKE_CREDENTIALS }}
        project_id: ${{ secrets.PROJECT_ID }}
        export_default_credentials: true

    # Step to install required gcloud components
    - name: Install gcloud components
      run: gcloud components install kubectl gke-gcloud-auth-plugin

    # Step to configure kubectl to use the GKE cluster
    - name: Configure kubectl
      run: |
        gcloud container clusters get-credentials ${{ secrets.CLUSTER_NAME }} --region ${{ secrets.REGION }}

    # Step to apply Kubernetes manifests and deploy to GKE
    - name: Deploy to GKE
      run: |
        kubectl apply -f 1-hello-app-deployment.yaml
